Python: only set _der_packer if it is provided
 - Old code checked for der_packer is not None (comment on line
   40), new code did not, which replaces the class-property
   _der_packer which is set for most (all?) classes.
   Running tests led to these failures:

   17:   File "quick-der/python/quick_der/classes.py", line 441, in __init_bindata__
   17:     mytag = ord(self._der_packer[0]) & DER_PACK_MATCHBITS
   17: TypeError: 'NoneType' object has no attribute '__getitem__'

 - Do the same with context and recipe -- only set them if they're
   passed to the constructor, so preserving the class attribute.